-- Explain merge join in SQL. - Merge join produces a single output stream resulting from the joining of two sorted datasets using an INNER, FULL, or LEFT join. It is the most effective of all the operators for joining data. Specifically, merge join requires that both inputs be sorted as well as matching meta-data in the joined columns. Users can't join columns of different data types together. Users are not permitted to combine a column with a numeric data type with a column with a character data type. State the difference between inner join and left join.

-- MERGE INTO TargetTable AS table
-- USING SourceTable AS Start
-- ON table.KeyColumn
-- WHEN MATCHED THEN
-- UPDATE SET table.Columnname1, table.Columnname2 = S.Column2
-- WHEN NOT MATCHED BY TARGET THEN
-- INSERT (KeyColumn, Column1, Column2) VALUES (select.KeyColumn, select.Column1, select.Column2)
-- WHEN NOT MATCHED BY SOURCE THEN
-- DELETE;
